require:
  - solidus_dev_support/rubocop

Gemspec/RequiredRubyVersion:
  Enabled: false

AllCops:
  NewCops: disable

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5
